import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/utils/Provider/AuthProvider";
import { Toaster } from "react-hot-toast";
import ReactTanstackProvider from "@/utils/Provider/ReactTanstackProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactTanstackProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
          <Toaster />
        </ReactTanstackProvider>
      </body>
    </html>
  );
}